packages:
  # all packages in subdirs of components/
  - "rainbow-cli/**"
  - "rainbow-scss/**"
  - "rainbow-element/**"
  - "rainbow-js/**"
  - "react/r-hooks/**"
  - "react/r-view/**"
  - "vue/v-directives/**"
  - "vue/v-hooks/**"
  - "vue/v-views/**"
  - "vue/v-view/**"
  - "vue/v-chart/**"
  - "vue/v-library/**"
  - "vue/v-cli/**"
allowBuilds:
  core-js: set this to true or false
  core-js-pure: set this to true or false
  esbuild: set this to true or false
  vue-demi: set this to true or false
  yorkie: set this to true or false
